### ISSUE TITLE
Pandora login broken

### ISSUE THREAD

**Issue by bobbybrenman** [nixme/warble#20]
When I enter my credentials for pandora I get a quick spinner and then a fresh credentials prompt. Logging in to pandora directly works fine.

**Comment by arbales** [comment]
Yikes. This is happening for me too.

**Comment by arbales** [comment]
Assigned Gopal, since he's the only one with access to the logs.

**Comment by nixme** [comment]
Pandora updated their keys and protocol version. See https://github.com/PromyLOPh/pianobar/issues/107
