### ISSUE TITLE
Has the repo been rewritten again?

### ISSUE THREAD

**Issue by arbales** [nixme/warble#4]
Despite a pull, I'm still ahead of master by 5 commits — I'll delete and re-clone again, but if possible, could we avoid rewriting?

Could there be another explanation for this?

**Comment by nixme** [comment]
No it hasn't been rewritten. I've noticed this too. The new version of git seems to lie on `git status`. Try doing a `git fetch` and see if `git status` doesn't show that anymore.

**Comment by nixme** [comment]
I'm closing this since you've been able to properly push changes.

**Comment by arbales** [comment]
until the next rebase, sir.

**Comment by nixme** [comment]
I promise to not force push if you promise to not make commits that anger me. Deal?

**Comment by arbales** [comment]
Sorry, I can't comment on unreleased commits at this time. Thanks for your continued support.

## 

Austin Bales
Sent with Sparrow
